/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package APP_TIENDA;

/**
 *
 * @author RECIMET
 */
public class CREAR_PRODUCTO extends javax.swing.JFrame {

    /**
     * Creates new form CREAR_PRODUCTO
     */
    public CREAR_PRODUCTO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CODIGO = new javax.swing.JTextField();
        TIPO = new javax.swing.JTextField();
        NOMBRE = new javax.swing.JTextField();
        PRECIO = new javax.swing.JTextField();
        EXISTENCIA = new javax.swing.JTextField();
        CREAR = new javax.swing.JButton();
        AGREGAR = new javax.swing.JButton();
        ELIMINAR = new javax.swing.JButton();
        REGRESAR = new javax.swing.JButton();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CREAR PRODUCTO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 10, 500, 60);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CÓDIGO DE PRODUCTO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 110, 310, 20);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TIPO DE PRODUCTO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 150, 290, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NOMBRE DEL PRODUCTO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 190, 310, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PRECIO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 230, 210, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EXISTENCIA");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(170, 270, 210, 20);

        CODIGO.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(CODIGO);
        CODIGO.setBounds(360, 100, 250, 30);

        TIPO.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(TIPO);
        TIPO.setBounds(360, 140, 250, 30);

        NOMBRE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(NOMBRE);
        NOMBRE.setBounds(360, 180, 250, 30);

        PRECIO.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(PRECIO);
        PRECIO.setBounds(360, 220, 250, 30);

        EXISTENCIA.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(EXISTENCIA);
        EXISTENCIA.setBounds(360, 260, 250, 30);

        CREAR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CREAR.setText("CREAR NUEVO PRODUCTO");
        getContentPane().add(CREAR);
        CREAR.setBounds(10, 370, 280, 31);

        AGREGAR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AGREGAR.setText("AGREGAR");
        getContentPane().add(AGREGAR);
        AGREGAR.setBounds(150, 310, 140, 31);

        ELIMINAR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ELIMINAR.setText("ELIMINAR");
        getContentPane().add(ELIMINAR);
        ELIMINAR.setBounds(470, 310, 140, 31);

        REGRESAR.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        REGRESAR.setText("←");
        getContentPane().add(REGRESAR);
        REGRESAR.setBounds(540, 390, 73, 23);

        FONDO.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        FONDO.setForeground(new java.awt.Color(255, 255, 255));
        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/comida-rapida-fondo-madera-vieja-concepto-comida-chatarra-vista-superior-endecha-plana_104376-900.jpg"))); // NOI18N
        getContentPane().add(FONDO);
        FONDO.setBounds(0, 0, 670, 430);

        setSize(new java.awt.Dimension(642, 462));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CREAR_PRODUCTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CREAR_PRODUCTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CREAR_PRODUCTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CREAR_PRODUCTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CREAR_PRODUCTO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AGREGAR;
    private javax.swing.JTextField CODIGO;
    private javax.swing.JButton CREAR;
    private javax.swing.JButton ELIMINAR;
    private javax.swing.JTextField EXISTENCIA;
    private javax.swing.JLabel FONDO;
    private javax.swing.JTextField NOMBRE;
    private javax.swing.JTextField PRECIO;
    private javax.swing.JButton REGRESAR;
    private javax.swing.JTextField TIPO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
