/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package APP_TIENDA;

/**
 *
 * @author RECIMET
 */
public class MENU extends javax.swing.JFrame {

    /**
     * Creates new form MENU
     */
    public MENU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTT_PRODUCTOS = new javax.swing.JButton();
        BTT_PEDIDOS = new javax.swing.JButton();
        REGRESAR = new javax.swing.JButton();
        APP_TIENDA = new javax.swing.JLabel();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        BTT_PRODUCTOS.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BTT_PRODUCTOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/business_packages_boxes_products_sellingproducts_thereport_2344.png"))); // NOI18N
        BTT_PRODUCTOS.setText("PRODUCTOS");
        getContentPane().add(BTT_PRODUCTOS);
        BTT_PRODUCTOS.setBounds(340, 60, 280, 150);

        BTT_PEDIDOS.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BTT_PEDIDOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/Ordering_25406.png"))); // NOI18N
        BTT_PEDIDOS.setText("PEDIDOS");
        getContentPane().add(BTT_PEDIDOS);
        BTT_PEDIDOS.setBounds(340, 230, 280, 140);

        REGRESAR.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        REGRESAR.setText("←");
        getContentPane().add(REGRESAR);
        REGRESAR.setBounds(550, 380, 73, 23);

        APP_TIENDA.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        APP_TIENDA.setForeground(new java.awt.Color(255, 255, 255));
        APP_TIENDA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        APP_TIENDA.setText("APP TIENDA");
        getContentPane().add(APP_TIENDA);
        APP_TIENDA.setBounds(180, 0, 293, 56);

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/salchichas-caseras-sobre-fondo-piedra-espacio-copia-su-prueba_156140-1242.jpg"))); // NOI18N
        getContentPane().add(FONDO);
        FONDO.setBounds(0, 0, 626, 417);

        setSize(new java.awt.Dimension(643, 454));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel APP_TIENDA;
    private javax.swing.JButton BTT_PEDIDOS;
    private javax.swing.JButton BTT_PRODUCTOS;
    private javax.swing.JLabel FONDO;
    private javax.swing.JButton REGRESAR;
    // End of variables declaration//GEN-END:variables
}
