/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package APP_TIENDA;

/**
 *
 * @author RECIMET
 */
public class PEDIDOS extends javax.swing.JFrame {

    /**
     * Creates new form PEDIDOS
     */
    public PEDIDOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        T_PEDIDOS = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ENVIAR = new javax.swing.JButton();
        CANCELAR = new javax.swing.JButton();
        ENVIADO2 = new javax.swing.JButton();
        REGRESAR = new javax.swing.JButton();
        PANEL_CLIENTE = new javax.swing.JPanel();
        PANEL_TABLA = new javax.swing.JScrollPane();
        TABLA_CLIENTE = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        PANEL_PEDIDO = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLA_PEDIDO = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PEDIDOS = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABLA_CONSULTA = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        T_PEDIDOS.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        T_PEDIDOS.setText("PEDIDOS");
        getContentPane().add(T_PEDIDOS);
        T_PEDIDOS.setBounds(550, 50, 240, 50);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("TOTAL");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 470, 110, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("MONTO DE PAGO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 550, 220, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("CAMBIO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(250, 640, 140, 40);

        ENVIAR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ENVIAR.setText("ENVIAR PEDIDO");
        getContentPane().add(ENVIAR);
        ENVIAR.setBounds(20, 750, 177, 31);

        CANCELAR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CANCELAR.setText("CANCELAR PEDIDO");
        getContentPane().add(CANCELAR);
        CANCELAR.setBounds(220, 750, 207, 30);

        ENVIADO2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ENVIADO2.setText("PEDIDO ENVIADO");
        getContentPane().add(ENVIADO2);
        ENVIADO2.setBounds(450, 750, 210, 30);

        REGRESAR.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        REGRESAR.setText("←");
        getContentPane().add(REGRESAR);
        REGRESAR.setBounds(10, 10, 73, 23);

        PANEL_CLIENTE.setLayout(null);

        TABLA_CLIENTE.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TABLA_CLIENTE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        PANEL_TABLA.setViewportView(TABLA_CLIENTE);

        PANEL_CLIENTE.add(PANEL_TABLA);
        PANEL_TABLA.setBounds(0, 40, 550, 90);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("INFORMACION DEL CLIENTE");
        PANEL_CLIENTE.add(jLabel1);
        jLabel1.setBounds(10, 10, 360, 20);

        getContentPane().add(PANEL_CLIENTE);
        PANEL_CLIENTE.setBounds(240, 110, 550, 130);

        PANEL_PEDIDO.setLayout(null);

        TABLA_PEDIDO.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TABLA_PEDIDO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TABLA_PEDIDO);

        PANEL_PEDIDO.add(jScrollPane1);
        jScrollPane1.setBounds(0, 40, 550, 170);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("DETALLE DEL PEDIDO");
        PANEL_PEDIDO.add(jLabel2);
        jLabel2.setBounds(10, 10, 280, 20);

        getContentPane().add(PANEL_PEDIDO);
        PANEL_PEDIDO.setBounds(240, 260, 550, 210);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("PEDIDOS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 10, 140, 14);

        PEDIDOS.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        PEDIDOS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PEDIDOS EN PROCESO", "PEDIDOS ENVIADOS", "PEDIDOS CANCELADOS", "PEDIDOS ENTREGADOS" }));
        PEDIDOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PEDIDOSActionPerformed(evt);
            }
        });
        jPanel1.add(PEDIDOS);
        PEDIDOS.setBounds(10, 40, 160, 20);

        TABLA_CONSULTA.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TABLA_CONSULTA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TABLA_CONSULTA);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 90, 210, 150);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(580, 480, 210, 240);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 500, 230, 40);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(240, 590, 230, 40);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(240, 680, 230, 40);

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/hamburger-background-one-cheeseburger-two-hamburgers-onion-rings-french-fries-over-abstract-70668816.jpg"))); // NOI18N
        getContentPane().add(FONDO);
        FONDO.setBounds(0, 0, 850, 790);

        setSize(new java.awt.Dimension(813, 828));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PEDIDOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PEDIDOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PEDIDOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PEDIDOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PEDIDOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PEDIDOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PEDIDOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PEDIDOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CANCELAR;
    private javax.swing.JButton ENVIADO2;
    private javax.swing.JButton ENVIAR;
    private javax.swing.JLabel FONDO;
    private javax.swing.JPanel PANEL_CLIENTE;
    private javax.swing.JPanel PANEL_PEDIDO;
    private javax.swing.JScrollPane PANEL_TABLA;
    private javax.swing.JComboBox PEDIDOS;
    private javax.swing.JButton REGRESAR;
    private javax.swing.JTable TABLA_CLIENTE;
    private javax.swing.JTable TABLA_CONSULTA;
    private javax.swing.JTable TABLA_PEDIDO;
    private javax.swing.JLabel T_PEDIDOS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
