/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package APP_TIENDA;

/**
 *
 * @author RECIMET
 */
public class PRODUCTOS extends javax.swing.JFrame {

    /**
     * Creates new form PRODUCTOS
     */
    public PRODUCTOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLA_PEDIDOS = new javax.swing.JTable();
        REGRESAR = new javax.swing.JButton();
        CARTA_DEGUSTACIÓN = new javax.swing.JLabel();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        TABLA_PEDIDOS.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TABLA_PEDIDOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TABLA_PEDIDOS);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(230, 260, 870, 340);

        REGRESAR.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        REGRESAR.setText("←");
        getContentPane().add(REGRESAR);
        REGRESAR.setBounds(1150, 730, 73, 23);

        CARTA_DEGUSTACIÓN.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        CARTA_DEGUSTACIÓN.setText("MENÚ DEGUSTACIÓN");
        getContentPane().add(CARTA_DEGUSTACIÓN);
        CARTA_DEGUSTACIÓN.setBounds(230, 190, 640, 60);

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/la-bandera-o-el-fondo-horizontal-con-marco-consistió-en-diversos-comida-comidas-y-lugar-mexicanos-para-texto-burrito-109257401.jpg"))); // NOI18N
        FONDO.setText("jLabel1");
        getContentPane().add(FONDO);
        FONDO.setBounds(0, 0, 1260, 860);

        setSize(new java.awt.Dimension(1272, 814));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRODUCTOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRODUCTOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRODUCTOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRODUCTOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRODUCTOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CARTA_DEGUSTACIÓN;
    private javax.swing.JLabel FONDO;
    private javax.swing.JButton REGRESAR;
    private javax.swing.JTable TABLA_PEDIDOS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
