//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Capa_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Dirección { get; set; }
    }
}
