//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Capa_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos
    {
        public string Fecha { get; set; }
        public string Numero_pedido { get; set; }
        public string Codigo_cliente { get; set; }
        public string Nombre_cliente { get; set; }
        public string Codigo_producto { get; set; }
        public string Producto { get; set; }
        public int Precio { get; set; }
        public string Estado { get; set; }
        public string Dirección { get; set; }
    }
}
